spring:
  datasource:
    url: jdbc:h2:mem:companies-contacts-db
    username: sa
    password: pwd
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jackson:
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true
server:
  servlet:
    contextPath: /v1

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs