-- Addresses
INSERT INTO ADDRESS(ID, CITY, MUNICIPALITY, STREET_NAME, STREET_NUMBER) VALUES (1, 'Brussels', 'Brussels', 'Rue Haute', '1A');
INSERT INTO ADDRESS(ID, CITY, MUNICIPALITY, STREET_NAME, STREET_NUMBER)  VALUES (2, 'Brussels', 'Jette', 'Rue de la Victoire', '10');
-- Contacts
INSERT INTO CONTACT(ID, FIRST_NAME, LAST_NAME, CONTACT_TYPE, VAT_NUMBER, ADDRESS_ID) VALUES (1, 'John', 'Doe', 'EMPLOYEE', null, 1);
INSERT INTO CONTACT(ID, FIRST_NAME, LAST_NAME, CONTACT_TYPE, VAT_NUMBER, ADDRESS_ID) VALUES (2, 'Jane', 'Doe', 'FREELANCE', 'BE1548632514', 1);
-- Companies
INSERT INTO COMPANY(ID, NAME, VAT_NUMBER, ADDRESS_ID) VALUES (1, 'The Company', 'BE1235621547', 2);
-- Companies contacts
--INSERT INTO COMPANY_CONTACT(COMPANY_ID, CONTACT_ID) VALUES (1, 1);
--INSERT INTO COMPANY_CONTACT(COMPANY_ID, CONTACT_ID) VALUES (1, 2);